# Generated by Django 2.1.4 on 2019-02-17 00:04

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion
import djmoney.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BillyInvoiceContact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('synced', models.BooleanField(default=False)),
                ('billy_id', models.CharField(max_length=12, null=True)),
                ('billy_person_id', models.CharField(max_length=12, null=True)),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('company', 'company'), ('person', 'person')], max_length=12)),
                ('person_name', models.CharField(max_length=255, null=True)),
                ('person_email', models.EmailField(max_length=255, null=True)),
                ('person_id', models.CharField(max_length=12, null=True)),
                ('country_code', models.CharField(max_length=3)),
                ('street', models.CharField(max_length=255, null=True)),
                ('city_text', models.CharField(max_length=255, null=True)),
                ('zipcode_text', models.CharField(max_length=255, null=True)),
                ('phone', models.CharField(max_length=255, null=True)),
                ('registration_no', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('synced', models.BooleanField(default=False)),
                ('ticketbutler_orderid', models.CharField(max_length=16)),
                ('billy_invoice_id', models.CharField(max_length=16)),
                ('billy_product_id', models.CharField(max_length=16)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('when', models.DateTimeField()),
                ('price_currency', djmoney.models.fields.CurrencyField(choices=[('DKK', 'Danish Krone'), ('EUR', 'Euro')], default='XYZ', editable=False, max_length=3)),
                ('price', djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0.0'), max_digits=14)),
                ('vat', models.DecimalField(choices=[('0.00', Decimal('0')), ('0.25', Decimal('0.25'))], decimal_places=2, default=Decimal('0.25'), max_digits=6)),
                ('amount', models.SmallIntegerField(default=1)),
                ('ticket_type_name', models.CharField(max_length=255)),
                ('pdf', models.FileField(upload_to='')),
                ('billy_contact', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='invoices.BillyInvoiceContact')),
            ],
        ),
    ]
