# Generated by Django 2.1.4 on 2019-02-17 00:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0002_auto_20190217_0025'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice',
            old_name='billy_invoice_id',
            new_name='billy_id',
        ),
    ]
