# Generated by Django 2.1.4 on 2019-02-17 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0003_auto_20190217_0036'),
    ]

    operations = [
        migrations.AddField(
            model_name='billyinvoicecontact',
            name='ticketbutler_orderid',
            field=models.CharField(default='', max_length=16),
        ),
    ]
