# Generated by Django 2.1.4 on 2019-02-18 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0004_billyinvoicecontact_ticketbutler_orderid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billyinvoicecontact',
            name='billy_id',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='billyinvoicecontact',
            name='billy_person_id',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='billyinvoicecontact',
            name='person_id',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='billyinvoicecontact',
            name='ticketbutler_orderid',
            field=models.CharField(default='', max_length=32),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='billy_id',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='billy_product_id',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='ticketbutler_orderid',
            field=models.CharField(max_length=32),
        ),
    ]
