# Generated by Django 2.1.4 on 2019-02-19 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0006_auto_20190219_2041'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketbutlerticket',
            name='sprints',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, 'no'), (1, 'maybe'), (2, 'yes')], null=True),
        ),
    ]
