# Generated by Django 2.1.4 on 2019-02-21 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0007_ticketbutlerticket_sprints'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='billy_payment_id',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
