# Generated by Django 2.1.4 on 2019-02-22 20:56

from decimal import Decimal

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0009_auto_20190221_2238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billyinvoicecontact',
            name='country_code',
            field=models.CharField(max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='vat',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.25'), max_digits=6),
        ),
    ]
