# Generated by Django 2.1.4 on 2019-02-22 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0010_auto_20190222_2056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billyinvoicecontact',
            name='country_code',
            field=models.CharField(default='DK', max_length=3),
        ),
    ]
