# Generated by Django 2.1.4 on 2019-03-03 23:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0011_auto_20190222_2102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketbutlerticket',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='invoices.Invoice'),
        ),
    ]
