# Generated by Django 2.1.4 on 2019-03-04 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0012_auto_20190303_2344'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketbutlerticket',
            name='invited',
            field=models.BooleanField(default=False, help_text='Invitation to create a user account sent'),
        ),
    ]
