# Generated by Django 2.1.4 on 2019-03-11 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0013_ticketbutlerticket_invited'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketbutlerticket',
            name='invited_when',
            field=models.DateTimeField(editable=False, null=True),
        ),
    ]
