# Generated by Django 2.1.4 on 2019-03-18 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0016_invoice_to_invoices'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='ticketbutler_order_line_no',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
