# Generated by Django 2.1.4 on 2019-03-19 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0017_invoice_ticketbutler_order_line_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketbutlerticket',
            name='free_ticket',
            field=models.BooleanField(default=False, help_text='Ticket was free (and has no invoice)'),
        ),
    ]
