# Generated by Django 2.1.4 on 2019-03-19 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0018_ticketbutlerticket_free_ticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketbutlerticket',
            name='ticketbutler_ticket_type_name',
            field=models.CharField(default='', max_length=255),
        ),
    ]
