# Generated by Django 2.1.4 on 2019-04-02 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0019_ticketbutlerticket_ticketbutler_ticket_type_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketbutlerticket',
            name='refunded',
            field=models.BooleanField(default=False, help_text='Ticket was free (and has no invoice)'),
        ),
    ]
