# Generated by Django 2.1.4 on 2019-03-03 23:47

import datetime
from decimal import Decimal

import django.db.models.deletion
import djmoney.models.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BicycleBooking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confirmed', models.BooleanField(default=False)),
                ('days', models.PositiveSmallIntegerField(default=1)),
                ('from_date', models.DateField(default=datetime.date.today)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='BikeType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('size', models.CharField(max_length=255)),
                ('price_per_day_currency', djmoney.models.fields.CurrencyField(choices=[('DKK', 'Danish Krone'), ('EUR', 'Euro')], default='XYZ', editable=False, max_length=3)),
                ('price_per_day', djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0.0'), max_digits=14)),
            ],
        ),
        migrations.AddField(
            model_name='bicyclebooking',
            name='bike_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ticketholders.BikeType'),
        ),
        migrations.AddField(
            model_name='bicyclebooking',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
