# Generated by Django 2.1.4 on 2019-03-07 02:03

import datetime
from decimal import Decimal

import django.db.models.deletion
import djmoney.models.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BicycleBooking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confirmed', models.BooleanField(default=False, help_text='Please check or un-check this field so we can understand whether this booking is confirmed or not.')),
                ('size', models.CharField(choices=[('small', 'Small (your height <168 cm)'), ('medium', 'Medium (your height 165-180cm)'), ('large', 'Large (your height >178cm)')], default='medium', max_length=255)),
                ('frame_type', models.PositiveSmallIntegerField(blank=True, choices=[(None, 'Undecided'), (0, 'Straight bar'), (1, 'Step-trough')], default=None, null=True)),
                ('days', models.PositiveSmallIntegerField(choices=[(3, '3 days'), (4, '4 days'), (5, '5 days'), (6, '6 days'), (7, '7 week'), (8, 'Over a week')], default=3)),
                ('from_date', models.DateField(default=datetime.date.today)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='BicycleType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price_per_day_currency', djmoney.models.fields.CurrencyField(choices=[('DKK', 'Danish Krone'), ('EUR', 'Euro')], default='XYZ', editable=False, max_length=3)),
                ('price_per_day', djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0'), help_text='Not displayed to people right now, there is a table further down', max_digits=14)),
            ],
            options={
                'ordering': ('price_per_day', 'name'),
            },
        ),
        migrations.AddField(
            model_name='bicyclebooking',
            name='bicycle_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ticketholders.BicycleType'),
        ),
        migrations.AddField(
            model_name='bicyclebooking',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
