# Generated by Django 2.1.4 on 2019-03-13 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketholders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bicyclebooking',
            name='confirmed',
            field=models.BooleanField(default=False, help_text='Check this field to confirm your intention to pick up a bike.'),
        ),
    ]
