# Generated by Django 2.1.4 on 2019-03-04 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketholders', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='biketype',
            options={'ordering': ('price_per_day', 'name', 'size')},
        ),
        migrations.AlterField(
            model_name='bicyclebooking',
            name='confirmed',
            field=models.BooleanField(default=False, help_text='Please check or un-check this field so we can understand whether this booking is confirmed or not.'),
        ),
    ]
