# Generated by Django 2.1.4 on 2019-03-18 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketholders', '0002_noop_confirmed_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bicyclebooking',
            name='days',
            field=models.PositiveSmallIntegerField(choices=[(3, '3 days'), (4, '4 days'), (5, '5 days'), (6, '6 days'), (7, '1 week'), (8, 'Over a week')], default=3),
        ),
        migrations.AlterField(
            model_name='bicyclebooking',
            name='frame_type',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(None, 'Undecided'), (0, 'Straight bar'), (1, 'Step-through')], default=None, null=True),
        ),
    ]
