# Generated by Django 2.1.4 on 2019-03-07 01:18

from decimal import Decimal

import django.db.models.deletion
import djmoney.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketholders', '0002_auto_20190304_2121'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='biketype',
            options={'ordering': ('price_per_day', 'name')},
        ),
        migrations.RemoveField(
            model_name='biketype',
            name='size',
        ),
        migrations.AddField(
            model_name='bicyclebooking',
            name='frame_type',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(None, 'Undecided'), (0, 'Straight bar'), (1, 'Step-trough')], default=None, null=True),
        ),
        migrations.AddField(
            model_name='bicyclebooking',
            name='size',
            field=models.CharField(choices=[('small', 'Small'), ('medium', 'Medium'), ('large', 'Large')], default='medium', max_length=255),
        ),
        migrations.AlterField(
            model_name='bicyclebooking',
            name='bike_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ticketholders.BikeType'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bicyclebooking',
            name='days',
            field=models.PositiveSmallIntegerField(choices=[(3, '3 days'), (4, '4 days'), (5, '5 days'), (6, '6 days'), (7, '7 week'), (8, 'Over a week')], default=3),
        ),
        migrations.AlterField(
            model_name='biketype',
            name='price_per_day',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0.0'), help_text='Not displayed to people right now, there is a table further down', max_digits=14),
        ),
    ]
