# Generated by Django 2.1.4 on 2019-03-30 21:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketholders', '0003_auto_20190318_2131'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Used to send this email from CLI', max_length=255, unique=True)),
                ('template_content', models.TextField(help_text="Unsubscribe links are automatically added at the bottom. Remember to add a good footer, and start it with '--' and linebreak")),
                ('subject', models.CharField(max_length=255)),
                ('newsletter', models.BooleanField(default=True, help_text='Creates an unsubscribe link for newsletter subscribers.')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('count', models.PositiveSmallIntegerField(default=0)),
                ('first_time_send', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Recipient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('sent', models.BooleanField(default=False)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('email_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipients', to='ticketholders.EmailTemplate')),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='recipient',
            unique_together={('email_template', 'email')},
        ),
    ]
