# Generated by Django 2.1.4 on 2019-04-05 20:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pretalx_utils', '0008_voucher_codes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ticketholders', '0005_subscription_confirmed'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkshopAttending',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('workshop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workshop_attendees', to='pretalx_utils.TalkExtraProperties')),
            ],
        ),
    ]
