# Generated by Django 2.1.4 on 2019-03-02 17:22

import dceu2019.apps.pretalx_utils.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('submission', '0030_auto_20181209_2229'),
    ]

    operations = [
        migrations.CreateModel(
            name='TalkExtraProperties',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employer_sponsor_name', models.CharField(blank=True, max_length=255, null=True)),
                ('twitter_card_image', models.ImageField(blank=True, null=True, upload_to=dceu2019.apps.pretalx_utils.models.twitter_card_path)),
                ('keynote', models.BooleanField(default=False)),
                ('published', models.BooleanField(default=False)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='submission.Submission')),
            ],
        ),
    ]
