# Generated by Django 2.1.4 on 2019-03-13 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pretalx_utils', '0004_auto_20190312_2217'),
    ]

    operations = [
        migrations.AddField(
            model_name='talkextraproperties',
            name='employer_attribution',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='talkextraproperties',
            name='employer_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
