# Generated by Django 2.1.4 on 2019-03-14 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pretalx_utils', '0005_employer_attribution'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='talkextraproperties',
            name='employer_sponsor_name',
        ),
    ]
