# Generated by Django 2.1.4 on 2019-03-24 22:06
import random

from django.db import migrations


def generate_voucher_codes(apps, schema_editor):
    """
    We used to have a single invoice per ticket, now we can have several
    invoices because we cannot tell which order_line in Ticketbutler data
    belongs to which ticket, and we are not able to create combined invoices
    with our current API iteration structure... unless someone stays up for
    some more nights :)
    """
    TalkExtraProperties = apps.get_model('pretalx_utils', 'TalkExtraProperties')
    for talk in TalkExtraProperties.objects.filter(ticket_voucher=""):
        talk.ticket_voucher = "speaker-" + talk.slug.replace("-", "")[:20] + "-{:06d}".format(random.randint(0, 1000000))
        talk.save()


class Migration(migrations.Migration):

    dependencies = [
        ('pretalx_utils', '0007_vouchers'),
    ]

    operations = [
        migrations.RunPython(generate_voucher_codes),
    ]
