# Generated by Django 2.1.4 on 2019-04-05 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pretalx_utils', '0008_voucher_codes'),
    ]

    operations = [
        migrations.AddField(
            model_name='talkextraproperties',
            name='max_attendance',
            field=models.PositiveSmallIntegerField(blank=True, default=None, help_text='Max attendance (for workshops)', null=True),
        ),
    ]
