# Generated by Django 2.1.4 on 2019-04-19 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pretalx_utils', '0009_talkextraproperties_max_attendance'),
    ]

    operations = [
        migrations.AddField(
            model_name='talkextraproperties',
            name='youtube_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
