# Generated by Django 2.1.4 on 2019-04-21 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pretalx_utils', '0010_talkextraproperties_youtube_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='talkextraproperties',
            name='youtube_url',
        ),
        migrations.AddField(
            model_name='talkextraproperties',
            name='youtube_id',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
